### ISSUE TITLE
Cache platform zips downloaded via `android update` command

### ISSUE THREAD

**Issue by patcon** [gildegoma/chef-android-sdk#19]
Inconveniently, the `android update` command immediately deletes any zips that it downloads into its `temp/` directory, and it offers no caching functionality. I've experimented a bit with an approach that watches the temp directory for new zip files, and changes the user's owner to root. If you have first changed the temp dir's *group* to "root", and set the sticky bit on that dir, then the regular user (and the android command) won't be able to delete the zip after downloading. We can then move the zips into a cache somewhere.

These two articles contain the details needed:
- https://unix.stackexchange.com/questions/20104/is-there-any-way-to-prevent-deletion-of-certain-files-from-user-owned-directory
- https://unix.stackexchange.com/questions/24952/script-to-monitor-folder-for-new-files

Thinking that if we can set up a daemon service running a watcher via inotifywait, we can change the owner of the zip and make sure that all zips stay there.

Anyhow, this isn't super pressing for me right now, but wanted to get the technique in an issue in case anyone else was interested in caching later

**Comment by gildegoma** [comment]
@patcon Sorry for lack of response during all this time. 

I'm closing this, as I am I think that such kind of caching feature should better be solved in an other place, ideally in official google's `android` tooling. Adding and maintaining this kind of feature looks a lot of effort in comparison of the "network bandwidth effort" of living without file caching.

Please feel free to provide further arguments (I always can re-open it ;-)
