### ISSUE TITLE
Cut new release to supermarket

### ISSUE THREAD

**Issue by patcon** [gildegoma/chef-android-sdk#23]
Yes, it's possible to use the git tags or commit refs, but it's nice to be able to easily use the version constraints in a berksfile :)

**Comment by patcon** [comment]
[stove](https://github.com/sethvargo/stove) makes for simple releases fyi!

**Comment by gildegoma** [comment]
@patcon thanks for pinging me about this long overdue. Yeah, I do [love Stove](https://github.com/sethvargo/stove/stargazers?page=3) as well, and I agree that should be using it more frequently ;-)

So, I finally released [0.2.0](https://supermarket.chef.io/cookbooks/android-sdk/versions/0.2.0#changelog) to Supermarket. Help welcome to work on the [0.3.0 milestone](https://github.com/gildegoma/chef-android-sdk/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.3.0)!

//cc @dhoer @rjaros87
