### ISSUE TITLE
Add .chefignore

### ISSUE THREAD

**Issue by rjaros87** [gildegoma/chef-android-sdk#30]
Exclude directory/files that are useless for Chef Server

**Comment by gildegoma** [comment]
I don't want to support/maintain a `.chefignore` "blocked list" file.

Releases are made with the very handy [Stove](https://github.com/sethvargo/stove) tool, producing packages based on a ["allowed list"](https://github.com/sethvargo/stove/blob/b512213255586301d20ac7b518c9733aa1b7455a/lib/stove/packager.rb#L10-L25) principle.
