### ISSUE TITLE
Override of android-sdk version is ignored

### ISSUE THREAD

**Issue by matskiv** [gildegoma/chef-android-sdk#31]
Hello,
I am trying to override android sdk version and checksum:
`override['android-sdk']['version'] = '24.4.1''`
`override['android-sdk']['checksum'] = 'e16917ad685...4650435e9'`
checksum override works but version override is ignored and version specified as default in chef-android-sdk is downloaded.

Can this be because of [this line](https://github.com/gildegoma/chef-android-sdk/blob/master/attributes/default.rb#L10) or is it more likely due to order of the cookbooks ?

**Comment by rjaros87** [comment]
Where do you try overridden? Can you provide some code?

**Comment by matskiv** [comment]
In my cookbook I include chef-android-sdk cookbook in _/recipes/android.rb_ file:
`include_recipe 'android-sdk::default'`

and in _/attributes/android.rb_ I have the override
`override['android-sdk']['version'] = '24.4.1'`
`override['android-sdk']['checksum'] = 'e16917ad685c1...694650435e9'`

There is almost no other code related to this.

**Comment by rjaros87** [comment]
In _/attributes/android.rb_ use `node.default['android-sdk']['version'] = '24.4.1'` or `node.override['android-sdk']['version'] = '24.4.1'`
Or in _/attributes/**default.rb**_  use `default['android-sdk']['version'] = '24.4.1'` or `override['android-sdk']['version'] = '24.4.1'`
Above solutions should resolve your problem.

**Comment by matskiv** [comment]
@rjaros87 Thank you for suggestion, it worked for me. :+1:
