### ISSUE TITLE
Broken for new SDK tools

### ISSUE THREAD

**Issue by zaiddabaeen** [gildegoma/chef-android-sdk#34]
The new URL has changed for the SDK tools and it uses `sdkmanager` from now on. This cookbook does not work for the new versions.

**Comment by gildegoma** [comment]
As mentioned in https://github.com/rjaros87/chef-android-sdk/pull/2#issuecomment-283580436, we'll first implement a "simple" backwards compatible fix in bug fix release `0.2.1`  (i.e. only targeting the Linux platform). Any help on this would be highly appreciated!

**Comment by rjaros87** [comment]
I'll prepare some copy of my code for cookbook 0.2.1

**Comment by gildegoma** [comment]
@rjaros87 you're awesome, thank you so much 😀

**Comment by gildegoma** [comment]
Fixed in master. The release will be published on Supermarket this week-end.
